######################################################################
# Automatically generated by qmake (3.0) Thu Aug 30 13:38:48 2018
######################################################################

TEMPLATE = app
TARGET = Colors
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += colordialog.h
SOURCES += colordialog.cpp main.cpp
