######################################################################
# Automatically generated by qmake (3.0) Wed Aug 29 16:38:48 2018
######################################################################

TEMPLATE = app
TARGET = ListWidget
INCLUDEPATH += .

QT += widgets

CONFIG += c++11


# Input
HEADERS += ListWidgetDialog.h
SOURCES += ListWidgetDialog.cpp main.cpp
