######################################################################
# Automatically generated by qmake (3.0) Tue Aug 28 16:11:01 2018
######################################################################

TEMPLATE = app
TARGET = listing1-10
INCLUDEPATH += .

QT += core widgets

# Input
HEADERS += myclass.h
SOURCES += main.cpp myclass.cpp
