######################################################################
# Automatically generated by qmake (3.0) Thu Aug 30 14:41:59 2018
######################################################################

TEMPLATE = app
TARGET = Fonts
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += fontdialog.h
SOURCES += fontdialog.cpp main.cpp
