######################################################################
# Automatically generated by qmake (3.0) Wed Aug 29 17:41:26 2018
######################################################################

TEMPLATE = app
TARGET = InputDialog
INCLUDEPATH += .

QT +=widgets core

CONFIG +=c++11

# Input
SOURCES += main.cpp
