######################################################################
# Automatically generated by qmake (3.0) Tue Aug 28 15:06:59 2018
######################################################################

TEMPLATE = app
TARGET = listing1-6
INCLUDEPATH += .

QT +=core

# Input
SOURCES += main.cpp
